version: "3.9"

services:
  base:
    build:
      context: .
      dockerfile: docker/Dockerfile.base
    image: otho/omicsplayground-base

  dev-renv:
    build: 
      context: .
      dockerfile: docker/Dockerfile.renv
    image: otho/omicsplayground-renv
    env_file:
      - .env
    ports:
      - 127.0.0.1:4000:3838
    volumes:
      - ${WORKDIR}:/home/project
      - "${RENV_CACHE_PATH}:/root/.cache/R/renv/cache/"
    command: bash -c "tail -F anything"


##version: '3.6'
##
##services:
##  orca-server:
##    container_name: orca-server
##    image: quay.io/plotly/orca:latest
##    restart: always
##    networks:
##      - play
##
##  playground:
##    container_name: playground
##    depends_on:
##      - orca-server
##    image: bigomics/omicsplayground:latest
##    volumes:
##      - /var/log/apache2:/omicsplayground/xlib/apache2.log      
####    - ./data:/omicsplayground/data
##    ports:
##      - 4000:3838
##    networks:
##      - play
##    restart: always
##    environment:
##      ORCA_SERVER: orca-server:9091
##
####volumes:
####   omxp_data: {}
##
##networks:
##  play:
##    driver: bridge
